Repository sledilnik/zdravniki, pull requests merged in 2021-12, with the labels that each got.

#60 Fix node 17 compatibility
  .npmrc
  .nvmrc
  yarn.lock
Labels: bug

#114 Use doctor type when finding doctor for doctor's page 🐛
  src/pages/Doctor.js
Labels: bug, deploy-preview

#110 UI improvements and fixes - attempt 2
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/styles/index.js
  src/components/Doctors/index.js
  src/components/Doctors/styles/index.js
  src/components/Filters/Search.js
  src/components/Filters/styles/Search.js
  src/components/Header/index.js
  src/components/Header/styles/index.js
  src/components/Shared/FooterInfo.js
  src/components/Shared/Loader.js
  src/pages/About.js
  src/pages/Doctor.js
  src/pages/Faq/index.js
  src/pages/Home.js
  src/pages/styles/Doctor.js
  src/pages/styles/Home.js
  src/pages/styles/Markdown.js
Labels: deploy-preview

#116 Add search by municipalityPart 🎯
  src/services/doctors.js
Labels: enhancement, deploy-preview

#119 feat: 👽️ remove doctor id
  src/components/DoctorCard/index.js
  src/components/Doctors/Map.js
  src/components/Doctors/Markers.js
  src/context/doctorsContext.js
  src/services/doctors.js
  src/utils/index.js
Labels: deploy-preview

#126 Add pediatrician to doctor type selection
  src/components/DoctorCard/Shared/index.js
  src/components/DoctorCard/dicts.js
  src/components/Filters/ToggleDoctorType.js
  src/components/Filters/index.js
  src/const/doctors.js
  src/locales/en.json
  src/locales/sl.json
Labels: deploy-preview

#120 Improved tooltip
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/ReportError/index.js
  src/components/DoctorCard/styles/index.js
  src/components/Doctors/Markers.js
  src/components/Doctors/styles/index.js
  src/components/Header/index.js
  src/index.css
  src/routes/index.js
Labels: deploy-preview

#122 fix(Home): 💄 zoom and filter state lost
  src/components/DoctorCard/index.js
  src/components/DoctorCard/styles/index.js
  src/components/Doctors/index.js
  src/components/Doctors/styles/index.js
Labels: deploy-preview

#125 Doctor card buttons => dropdown menu with labels
  src/assets/icon-alert.svg
  src/assets/icon-more.svg
  src/assets/icon-phone-none--big.svg
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/styles/index.js
  src/components/Doctors/styles/index.js
  src/components/Shared/Icons.js
  src/locales/en.json
  src/locales/sl.json
Labels: deploy-preview

#117 style: ⚰️ cleanup after #110 was merged
  src/components/DoctorCard/styles/index.js
  src/components/Filters/Search.js
  src/components/Filters/styles/Search.js
  src/pages/About.js
  src/pages/Faq/index.js
  src/pages/Home.js
  src/pages/styles/Home.js
Labels: deploy-preview

#140 fix: 💄 no border radius if age group not present
  src/components/DoctorCard/Shared/index.js
  src/components/DoctorCard/styles/PageInfo.js
Labels: deploy-preview

#143 FIX: Remove card area click to go to the dr page
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/styles/index.js
Labels: deploy-preview

#142 Mobile tooltip timeouts
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/PageInfo.js
Labels: deploy-preview

#146 Set min-width to map tooltips
  public/safari-pinned-tab.svg
  src/assets/icon-adults--white.svg
  src/assets/icon-adults.svg
  src/assets/icon-alert.svg
  src/assets/icon-all--white.svg
  src/assets/icon-all.svg
  src/assets/icon-back.svg
  src/assets/icon-ban--white.svg
  src/assets/icon-ban-red.svg
  src/assets/icon-ban.svg
  src/assets/icon-check--white.svg
  src/assets/icon-check-green.svg
  src/assets/icon-check.svg
  src/assets/icon-circle.svg
  src/assets/icon-close.svg
  src/assets/icon-dentist--white.svg
  src/assets/icon-dentist.svg
  src/assets/icon-family-dr--white.svg
  src/assets/icon-family-dr.svg
  src/assets/icon-fb.svg
  src/assets/icon-filter--white.svg
  src/assets/icon-filter.svg
  src/assets/icon-group.svg
  src/assets/icon-gynecologist--white.svg
  src/assets/icon-gynecologist.svg
  src/assets/icon-id-card.svg
  src/assets/icon-kids--white.svg
  src/assets/icon-kids.svg
  src/assets/icon-link.svg
  src/assets/icon-list-view--white.svg
  src/assets/icon-list-view.svg
  src/assets/icon-map-marker.svg
  src/assets/icon-map-view--white.svg
  src/assets/icon-map-view.svg
  src/assets/icon-more.svg
  src/assets/icon-phone--big.svg
  src/assets/icon-phone-none--big.svg
  src/assets/icon-phone.svg
  src/assets/icon-search--white.svg
  src/assets/icon-search.svg
  src/assets/icon-students--white.svg
  src/assets/icon-students.svg
  src/assets/icon-tw.svg
  src/assets/zdravniki-sledilnik-logo.svg
  src/index.css
Labels: deploy-preview

#145 fix: 🐛 filter state isn't preserved on return from
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/PageInfo.js
  src/components/Filters/ToggleDoctorType.js
Labels: deploy-preview

#139 ⚡ Only slugify once instead of at every search keypress
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/index.js
  src/pages/Doctor.js
  src/services/doctors.js
Labels: deploy-preview

#149 Fix: Remove request dict-doctors.csv
  src/components/DoctorCard/ReportError/index.js
  src/const/csvURL.js
  src/const/doctors.js
  src/context/doctorsContext.js
  src/context/filterContext.js
  src/pages/Doctor.js
  src/services/doctors.js
Labels: deploy-preview

#152 Rebased suppport multiple phone nums
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/PageInfo.js
  src/components/DoctorCard/Shared/Links.js
  src/components/DoctorCard/Shared/PageInfoPhones.js
  src/components/DoctorCard/Shared/PhoneButton.js
  src/components/DoctorCard/Shared/index.js
  src/components/DoctorCard/styles/PageInfo.js
  src/components/DoctorCard/styles/index.js
  src/components/Doctors/styles/index.js
Labels: deploy-preview

#156 Refactor DoctorCard
  src/components/DoctorCard/Info.js
  src/components/DoctorCard/Info/DoctorActions.js
  src/components/DoctorCard/Info/index.js
  src/components/DoctorCard/Map/MapEvents.js
  src/components/DoctorCard/Map/index.js
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/Shared/Accepts.js
  src/components/DoctorCard/Shared/index.js
Labels: deploy-preview

#162 Use doctor overrides
  src/components/DoctorCard/Info/index.js
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/Shared/Tooltips.js
  src/const/csvURL.js
  src/locales/en.json
  src/locales/sl.json
  src/services/doctors.js
Labels: deploy-preview

#166 Add insititution ID in path of doctor URL
  src/components/DoctorCard/Info/index.js
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/ReportError/index.js
  src/pages/Doctor.js
  src/routes/index.js
  src/services/doctors.js
Labels: deploy-preview

#167 Add instId, email, orderform to Report Error
  .env
  .env.development
  .env.example
  .env.production
  .env.staging
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/ReportError/index.js
  src/locales/en.json
  src/locales/sl.json
Labels: deploy-preview

#168 Design tweaks of the doctor page with label for override date/info
  src/assets/icon-booking.svg
  src/assets/icon-edit.svg
  src/assets/icon-email.svg
  src/assets/icon-link--big.svg
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/Shared/PageInfoPhones.js
  src/components/DoctorCard/Shared/Tooltips.js
  src/components/DoctorCard/styles/PageInfo.js
  src/components/DoctorCard/styles/index.js
  src/components/Shared/Icons.js
Labels: deploy-preview

#169 No results msg
  src/components/Doctors/index.js
  src/components/Shared/Loader.js
  src/locales/en.json
  src/locales/sl.json
Labels: deploy-preview

#170 Fix/tooltip
  src/components/DoctorCard/Info/index.js
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/Shared/Tooltips.js
  src/components/DoctorCard/Shared/index.js
  src/locales/en.json
  src/locales/sl.json
  src/services/doctors.js
Labels: deploy-preview

#173 feat: ✨ add timestamps
  src/App.js
  src/components/Shared/FooterInfo.js
  src/const/csvURL.js
  src/context/index.js
  src/context/timestampsContext.js
  src/hooks/useFetchTs.js
  src/locales/en.json
  src/locales/sl.json
Labels: deploy-preview

#174 feat: ✨ add snackbar alert on mobile in map view
  src/components/Doctors/MapOnlySnackbar.js
  src/components/Doctors/index.js
Labels: deploy-preview

#176 Fix/no institution
  src/services/doctors.js
Labels: deploy-preview

#81 🛂 Add missing react prop types
  .eslintrc.js
  package.json
  src/components/DoctorCard/Info/index.js
  src/components/DoctorCard/Map/index.js
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/Shared/Links.js
  src/components/DoctorCard/Shared/Tooltips.js
  src/components/DoctorCard/index.js
  src/components/Doctors/Map.js
  src/components/Doctors/Markers.js
  src/components/Doctors/index.js
  src/components/Filters/Shared/index.js
  src/components/Header/Drawer.js
  src/components/Shared/Chip.js
  src/components/Shared/CircleChart/index.js
  src/components/Shared/ExpandMore.js
  src/components/Shared/Leaflet/Markers.js
  src/components/Shared/Leaflet/index.js
  src/components/Shared/Loader.js
  src/components/Shared/Pagination.js
  src/components/Shared/ToggleGroup.js
  src/components/Shared/index.js
  src/context/doctorsContext.js
  src/context/filterContext.js
  src/context/leafletContext.js
  src/types/index.js
  yarn.lock
Labels: deploy-preview

#183 Remove edit route
  src/components/DoctorCard/Info/index.js
  src/components/DoctorCard/PageInfo/index.js
  src/components/DoctorCard/index.js
  src/pages/Doctor.js
  src/routes/index.js
Labels: deploy-preview
